# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 12:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('VEL', 'Vélo de route'), ('VTT', 'VTT'), ('CAP', 'Course à pied'), ('MAR', 'Marche'), ('AUT', 'Autre')], default='CAP', max_length=3)),
                ('ctime', models.DateTimeField(verbose_name='auto_now_add')),
                ('tdate', models.DateTimeField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gps.Trace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trace_point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('elevation', models.FloatField(null=True)),
                ('distance', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('heading', models.IntegerField(null=True)),
                ('heartrate', models.IntegerField(null=True)),
                ('cadence', models.IntegerField(null=True)),
                ('power', models.IntegerField(null=True)),
                ('temperature', models.IntegerField(null=True)),
                ('pression', models.IntegerField(null=True)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Trace')),
            ],
        ),
        migrations.CreateModel(
            name='Trace_point_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('trace_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Trace_point')),
            ],
        ),
        migrations.CreateModel(
            name='Trace_property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('value', models.CharField(max_length=255)),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Trace')),
            ],
        ),
        migrations.CreateModel(
            name='Trace_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('seconds', models.FloatField()),
                ('distance', models.FloatField()),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gps.Trace')),
            ],
        ),
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
